/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controllerDinas;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import model.modelLK;

/**
 *
 * @author sahriatus
 */
public class isiParam extends javax.swing.JFrame {

    modelLK mLK;
    Connection koneksi; 

    /**
     * Creates new form isiParam
     *
     */
    public isiParam() {
        mLK = new modelLK();
       
         
        initComponents();
    }
    
    public void cekListener(ActionListener a) {
        cek.addActionListener(a);
    }
    public void daftarListener(ActionListener a) {
        daftarLK.addActionListener(a);
    }
    public void sewaListener(ActionListener a) {
        sewa.addActionListener(a);
    }
    public void keluarListener(ActionListener a) {
        keluar.addActionListener(a);
    }
 
    public JLabel getIDLK() {
        return idLK;
    }

    public JLabel getLabelNoTanah() {
        return notanah;
    }

    public String getLuas() {
        return luas.getText();
    }

    public String getID() {
        return idLK.getText();
    }

    public String getSuhu() {
        return suhu.getText();
    }

    public String getKetinggian() {
        return ketinggian.getText();
    }

    public String getCurahHujan() {
        return debithujan.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daftarLK = new javax.swing.JButton();
        sewa = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        notanah = new javax.swing.JLabel();
        suhu = new javax.swing.JTextField();
        luas = new javax.swing.JTextField();
        cek = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        debithujan = new javax.swing.JTextField();
        notanah1 = new javax.swing.JLabel();
        ketinggian = new javax.swing.JTextField();
        idLK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daftarLK.setText(" ");
        daftarLK.setBorderPainted(false);
        daftarLK.setContentAreaFilled(false);
        getContentPane().add(daftarLK, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 150, 30));

        sewa.setText(" ");
        sewa.setBorderPainted(false);
        sewa.setContentAreaFilled(false);
        getContentPane().add(sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 73, 90, 30));

        kembali.setText(" ");
        kembali.setBorderPainted(false);
        kembali.setContentAreaFilled(false);
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 80, -1));
        getContentPane().add(notanah, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 68, 90, 30));

        suhu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        suhu.setBorder(null);
        suhu.setOpaque(false);
        suhu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhuActionPerformed(evt);
            }
        });
        getContentPane().add(suhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 170, 20));

        luas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        luas.setBorder(null);
        luas.setOpaque(false);
        luas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasActionPerformed(evt);
            }
        });
        getContentPane().add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 170, 20));

        cek.setText(" ");
        cek.setBorderPainted(false);
        cek.setContentAreaFilled(false);
        getContentPane().add(cek, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 80, -1));

        keluar.setText(" ");
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 50, -1));

        debithujan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        debithujan.setBorder(null);
        debithujan.setOpaque(false);
        debithujan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debithujanActionPerformed(evt);
            }
        });
        getContentPane().add(debithujan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, 20));

        notanah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/begron/Capture.PNG"))); // NOI18N
        getContentPane().add(notanah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 110, 70));

        ketinggian.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ketinggian.setBorder(null);
        ketinggian.setOpaque(false);
        ketinggian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketinggianActionPerformed(evt);
            }
        });
        getContentPane().add(ketinggian, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 170, 20));

        idLK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/begron/admin/2.2.jpg"))); // NOI18N
        getContentPane().add(idLK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasActionPerformed

    private void debithujanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debithujanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debithujanActionPerformed

    private void suhuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suhuActionPerformed

    private void ketinggianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketinggianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketinggianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(isiParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(isiParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(isiParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(isiParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cek;
    private javax.swing.JButton daftarLK;
    private javax.swing.JTextField debithujan;
    private javax.swing.JLabel idLK;
    private javax.swing.JButton keluar;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField ketinggian;
    private javax.swing.JTextField luas;
    private javax.swing.JLabel notanah;
    private javax.swing.JLabel notanah1;
    private javax.swing.JButton sewa;
    private javax.swing.JTextField suhu;
    // End of variables declaration//GEN-END:variables
}
