/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import model.modelLK;

/**
 *
 * @author Dheta
 */
public class lihatHasil extends javax.swing.JFrame {

    /**
     * Creates new form lihatHasil
     */    
    Connection koneksi;
    modelLK mLK;
    
    public lihatHasil() {
   
        mLK=new modelLK();
        initComponents();
    }
    
    public void setID(String id) {
        this.id.setText(id);
    }
    public void setTinggi(String tinggi) {
        this.tinggi.setText(tinggi);
    }
    public void setLuasP(String luasp) {
        this.luaspengairan.setText(luasp);
    }
    public void setSuhu(String suhu) {
        this.suhu.setText(suhu);
    }
    public void setHujan(String hujan) {
        this.hujan.setText(hujan);
    }
    public void setLuasT(String luas) {
        this.luastanah.setText(luas);
    }
    public void setAlamat(String alamat) {
        this.alamat.setText(alamat);
    }
    public void setPemilik(String pemilik) {
        this.pemilik.setText(pemilik);
    }
    public void setNoTanah(String notanah) {
        this.notanah.setText(notanah);
    }
    public void setHasil(String hasil) {
        this.hasil.setText(hasil);
    }
    public void sewaListener(ActionListener a) {
        sewa.addActionListener(a);
    }
    public void tolakListener(ActionListener a) {
        tolak.addActionListener(a);
    }
    public void keluarListener(ActionListener a) {
        keluar.addActionListener(a);
    }
    public void sewamenuListener(ActionListener a) {
        sewamenu.addActionListener(a);
    }
    public void lahanListener(ActionListener a) {
        lahan.addActionListener(a);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lahan = new javax.swing.JButton();
        sewamenu = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        tinggi = new javax.swing.JLabel();
        luaspengairan = new javax.swing.JLabel();
        suhu = new javax.swing.JLabel();
        hujan = new javax.swing.JLabel();
        luastanah = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        hasil = new javax.swing.JLabel();
        hasil1 = new javax.swing.JLabel();
        tolak = new javax.swing.JButton();
        sewa = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        pemilik = new javax.swing.JLabel();
        notanah = new javax.swing.JLabel();
        id1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lahan.setBorderPainted(false);
        lahan.setContentAreaFilled(false);
        getContentPane().add(lahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 140, 30));

        sewamenu.setBorderPainted(false);
        sewamenu.setContentAreaFilled(false);
        getContentPane().add(sewamenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, 90, 40));

        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 80, 30));

        tinggi.setText(" ");
        getContentPane().add(tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 20));

        luaspengairan.setText(" ");
        getContentPane().add(luaspengairan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 294, 170, 20));

        suhu.setText(" ");
        getContentPane().add(suhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 330, 150, 20));

        hujan.setText(" ");
        getContentPane().add(hujan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 174, 160, 20));

        luastanah.setText(" ");
        getContentPane().add(luastanah, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 214, 170, 20));

        alamat.setText(" ");
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 254, 180, 20));

        hasil.setText(" ");
        getContentPane().add(hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 334, 170, 20));

        hasil1.setText("dapat ditanami:");
        getContentPane().add(hasil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 319, 94, -1));

        tolak.setBorderPainted(false);
        tolak.setContentAreaFilled(false);
        getContentPane().add(tolak, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 80, 30));

        sewa.setBorderPainted(false);
        sewa.setContentAreaFilled(false);
        getContentPane().add(sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 100, 30));

        id.setText(" ");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 40, 20));

        pemilik.setText(" ");
        getContentPane().add(pemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 294, 170, 20));

        notanah.setText(" ");
        getContentPane().add(notanah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 170, 20));

        id1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/begron/b.jpg"))); // NOI18N
        id1.setText(" ");
        getContentPane().add(id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihatHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihatHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihatHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihatHasil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lihatHasil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel hasil;
    private javax.swing.JLabel hasil1;
    private javax.swing.JLabel hujan;
    private javax.swing.JLabel id;
    private javax.swing.JLabel id1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton lahan;
    private javax.swing.JLabel luaspengairan;
    private javax.swing.JLabel luastanah;
    private javax.swing.JLabel notanah;
    private javax.swing.JLabel pemilik;
    private javax.swing.JButton sewa;
    private javax.swing.JButton sewamenu;
    private javax.swing.JLabel suhu;
    private javax.swing.JLabel tinggi;
    private javax.swing.JButton tolak;
    // End of variables declaration//GEN-END:variables
}
