/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.Connection;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.modelLK;

/**
 *
 * @author sahriatus
 */
public class lihatIsiJadwal extends javax.swing.JFrame {

    /**
     * Creates new form lihatIsiJadwal
     */
    Connection koneksi;
    modelLK mLK;

    public lihatIsiJadwal() {
        mLK = new modelLK();
        initComponents();
    }

    public void setTabel(DefaultTableModel t) {
        tabel.setModel(t);
    }

    public JTable getTabel() {
        return tabel;
    }

    public JLabel getJadwal() {
        return jadwal;
    }

    public JButton getParameter() {
        return parameter;
    }

    public int getSelectedRow() {
        int baris = tabel.getSelectedRow();
        return baris;
    }

    public void addTableListener(MouseListener listener) {
        tabel.addMouseListener(listener);
    }

    public void tabelListener(MouseListener m) {
        tabel.addMouseListener(m);
    }

    public void isiParamListener(ActionListener listener) {
        parameter.addActionListener(listener);
    }

    public void kembaliListener(ActionListener listener) {
        kembali.addActionListener(listener);
    }
    public void keluarListener(ActionListener listener) {
        keluar.addActionListener(listener);
    }

    public void daftarListener(ActionListener listener) {
        daftarLK.addActionListener(listener);
    }

    public void sewaListener(ActionListener listener) {
        sewa.addActionListener(listener);
    }

    //buat ambil data dari baris yg diklik
    public int getBarisTerpilih() {
        return tabel.getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        daftarLK = new javax.swing.JButton();
        sewa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        keluar = new javax.swing.JButton();
        parameter = new javax.swing.JButton();
        jadwalnya = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        jadwal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daftarLK.setText(" ");
        daftarLK.setBorderPainted(false);
        daftarLK.setContentAreaFilled(false);
        getContentPane().add(daftarLK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 140, 30));

        sewa.setText(" ");
        sewa.setBorderPainted(false);
        sewa.setContentAreaFilled(false);
        getContentPane().add(sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 90, 30));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 450, 244));

        keluar.setText(" ");
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 50, -1));

        parameter.setText(" ");
        parameter.setBorderPainted(false);
        parameter.setContentAreaFilled(false);
        getContentPane().add(parameter, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 140, -1));
        getContentPane().add(jadwalnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 221, 53));

        kembali.setText(" ");
        kembali.setBorderPainted(false);
        kembali.setContentAreaFilled(false);
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 80, -1));

        jadwal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/begron/admin/2.1.jpg"))); // NOI18N
        getContentPane().add(jadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lihatIsiJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lihatIsiJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lihatIsiJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lihatIsiJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lihatIsiJadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarLK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jadwal;
    private javax.swing.JLabel jadwalnya;
    private javax.swing.JButton keluar;
    private javax.swing.JButton kembali;
    private javax.swing.JButton parameter;
    private javax.swing.JButton sewa;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
