/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import model.modelLK;

/**
 *
 * @author Dheta
 */
public class sewaDinas extends javax.swing.JFrame {

    /**
     * Creates new form sewaDinas
     */
    
    Connection koneksi;
    modelLK mLK;
    
    public sewaDinas() {
        mLK=new modelLK();
        initComponents();
    }
     public void setTabel(DefaultTableModel t) {
        tabel.setModel(t);
    }
 public void kembaliListener(ActionListener listener) {
        kembali.addActionListener(listener);
    }
 public void keluarListener(ActionListener listener) {
        keluar.addActionListener(listener);
    }
 public void jadwalListener(ActionListener listener) {
        jadwalsurvey.addActionListener(listener);
    }
 public void daftarLKListener(ActionListener listener) {
        daftarLK.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        daftarLK = new javax.swing.JButton();
        jadwalsurvey = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jadwalnya = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 500, 275));

        daftarLK.setText(" ");
        daftarLK.setBorderPainted(false);
        daftarLK.setContentAreaFilled(false);
        getContentPane().add(daftarLK, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 140, 30));

        jadwalsurvey.setText(" ");
        jadwalsurvey.setBorderPainted(false);
        jadwalsurvey.setContentAreaFilled(false);
        getContentPane().add(jadwalsurvey, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 110, 30));

        keluar.setText(" ");
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 50, -1));

        kembali.setText(" ");
        kembali.setBorderPainted(false);
        kembali.setContentAreaFilled(false);
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 80, -1));

        jadwalnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/begron/admin/3.0.jpg"))); // NOI18N
        getContentPane().add(jadwalnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 730, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sewaDinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sewaDinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sewaDinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sewaDinas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sewaDinas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton daftarLK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jadwalnya;
    private javax.swing.JButton jadwalsurvey;
    private javax.swing.JButton keluar;
    private javax.swing.JButton kembali;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
