/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import model.modelUser;

/**
 *
 * @author Akses
 */
public class signUp extends javax.swing.JFrame {

    /**
     * Creates new form signUp
     */
    
    Connection koneksi;
    modelUser muser;
    String namaJK[][];
    DateFormat date = DateFormat.getDateInstance();
    String tgllahir;
    private JFrame frame;
    
    public signUp() {
    muser=new modelUser() {
        @Override
        public boolean cekLogin(String username, String password) throws SQLException {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public boolean cekLevel(String username, String password) throws SQLException {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    };
    date = new SimpleDateFormat("yyyy-MM-dd");
        initComponents();
    }
    
    public void daftarPemilikListener(ActionListener a){
        daftar.addActionListener(a);
    }
    
  
    public String getNama() {
        return nama.getText();
    }
    public String getNoTelp() {
        return noTelepon.getText();
    }
    public String getNoKTP(){
        return noKTP.getText();
    }
    public String getAlamat() {
        return alamat.getText();
    }
    public String getTempatLahir(){
        return tempatLahir.getText();
    }
    public String getTanggalLahir() {
        String tgllahir1 = date.format(tanggalLahir.getDate());
        return tgllahir1;
    }
    public int getNamaJK(){
        int index=jenisKelamin.getSelectedIndex();
        return index;
    }
    public String getUsername() {
        return username.getText();
    }
    public String getPassword(){
        return password.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alamat1 = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        noKTP = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        tempatLahir = new javax.swing.JTextField();
        noTelepon = new javax.swing.JTextField();
        tanggalLahir = new com.toedter.calendar.JDateChooser();
        jenisKelamin = new javax.swing.JComboBox();
        alamat = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        daftar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        alamat1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        alamat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(alamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 120, 20));

        nama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nama.setBorder(null);
        nama.setOpaque(false);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 160, 20));

        noKTP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        noKTP.setBorder(null);
        noKTP.setOpaque(false);
        noKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noKTPActionPerformed(evt);
            }
        });
        getContentPane().add(noKTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 170, 20));

        username.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        username.setBorder(null);
        username.setOpaque(false);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 170, 20));

        tempatLahir.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        tempatLahir.setBorder(null);
        tempatLahir.setOpaque(false);
        tempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempatLahirActionPerformed(evt);
            }
        });
        getContentPane().add(tempatLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 120, 20));

        noTelepon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        noTelepon.setBorder(null);
        noTelepon.setOpaque(false);
        noTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTeleponActionPerformed(evt);
            }
        });
        getContentPane().add(noTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 170, 20));
        getContentPane().add(tanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 110, -1));

        jenisKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "laki-laki", "perempuan" }));
        getContentPane().add(jenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 220, 110, 30));

        alamat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        alamat.setBorder(null);
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 160, 20));

        password.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        password.setBorder(null);
        password.setOpaque(false);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 160, 20));

        daftar.setText(" ");
        daftar.setBorder(null);
        daftar.setBorderPainted(false);
        daftar.setContentAreaFilled(false);
        getContentPane().add(daftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 104, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/begron/a.jpg"))); // NOI18N
        jLabel9.setText(" ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void noTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTeleponActionPerformed

    private void noKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noKTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noKTPActionPerformed

    private void tempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempatLahirActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField alamat1;
    private javax.swing.JButton daftar;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jenisKelamin;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField noKTP;
    private javax.swing.JTextField noTelepon;
    private javax.swing.JTextField password;
    private com.toedter.calendar.JDateChooser tanggalLahir;
    private javax.swing.JTextField tempatLahir;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
