/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import model.modelLK;

/**
 *
 * @author Dheta
 */
public class tambahLK extends javax.swing.JFrame {

    /**
     * Creates new form tambahLK
     */
    Connection koneksi;
    modelLK mLK;
    String kec[][];
    String des[][];

    public tambahLK() {
        mLK = new modelLK();
        kecamatan = new JComboBox();
        desa = new JComboBox();
        kec = mLK.kecamatan();
        initComponents();
    }

    public String getKecamatan() {
        int indeks = kecamatan.getSelectedIndex();
        return kec[0][indeks];
    }

    public String getDesa() {
        int indeks = desa.getSelectedIndex();
        return des[0][indeks];
    }

    public String getNoTanah() {
        return noTanah.getText();
    }

    public String getAlamat() {
        return alamat.getText();
    }

    public String getLuas() {
        return luas.getText();
    }

    public void simpanListener(ActionListener a) {
        simpan.addActionListener(a);
    }
    public void keluarListener(ActionListener a) {
        keluar.addActionListener(a);
    }
    public void notifListener(ActionListener a) {
        notif.addActionListener(a);
    }
    public void sewaListener(ActionListener a) {
        sewa.addActionListener(a);
    }

    public void kembaliListener(ActionListener a) {
        kembali.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noTanah = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        luas = new javax.swing.JTextField();
        sewa = new javax.swing.JButton();
        notif = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        kecamatan = new javax.swing.JComboBox(kec[1]);
        desa = new javax.swing.JComboBox<String>();
        keluar = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noTanah.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        noTanah.setBorder(null);
        noTanah.setOpaque(false);
        noTanah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noTanahActionPerformed(evt);
            }
        });
        getContentPane().add(noTanah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 160, 20));

        alamat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        alamat.setBorder(null);
        alamat.setOpaque(false);
        alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatActionPerformed(evt);
            }
        });
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 160, 20));

        luas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        luas.setBorder(null);
        luas.setOpaque(false);
        luas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasActionPerformed(evt);
            }
        });
        getContentPane().add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 160, 20));

        sewa.setText(" ");
        sewa.setBorderPainted(false);
        sewa.setContentAreaFilled(false);
        getContentPane().add(sewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 110, -1));

        notif.setText(" ");
        notif.setBorderPainted(false);
        notif.setContentAreaFilled(false);
        getContentPane().add(notif, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 100, 30));

        kembali.setText(" ");
        kembali.setBorderPainted(false);
        kembali.setContentAreaFilled(false);
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 90, -1));

        kecamatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kecamatanActionPerformed(evt);
            }
        });
        getContentPane().add(kecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 140, -1));

        getContentPane().add(desa, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 140, -1));

        keluar.setText(" ");
        keluar.setBorderPainted(false);
        keluar.setContentAreaFilled(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 70, -1));

        simpan.setText(" ");
        simpan.setBorderPainted(false);
        simpan.setContentAreaFilled(false);
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 100, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/begron/pemilik/1.1.jpg"))); // NOI18N
        jLabel9.setText(" ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kecamatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kecamatanActionPerformed

        int kecamatan1 = kecamatan.getSelectedIndex();
        des = mLK.desa(Integer.valueOf(kec[0][kecamatan1]));
        desa.setModel(new DefaultComboBoxModel<>(des[1]));
    }//GEN-LAST:event_kecamatanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keluarActionPerformed

    private void noTanahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noTanahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noTanahActionPerformed

    private void alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatActionPerformed

    private void luasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahLK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahLK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JComboBox<String> desa;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> kecamatan;
    private javax.swing.JButton keluar;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField luas;
    private javax.swing.JTextField noTanah;
    private javax.swing.JButton notif;
    private javax.swing.JButton sewa;
    private javax.swing.JButton simpan;
    // End of variables declaration//GEN-END:variables
}
